# Generated by Django 3.2.3 on 2022-01-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.IntegerField(unique=True, verbose_name='Номер дела')),
                ('fam', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('fname', models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество')),
                ('dr', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
    ]
